[project]
name = "Music Analyser GUI"
version = "0.1.0"
description = "A GUI application for musicians to extract key features of a song quickly"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
